{% set name = "ElementEmbeddings" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/elementembeddings-{{ version }}.tar.gz
  sha256: 15064f5a3d436a68b66874da556a6a102c66c4077e4153181adcc6e6fec15504

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.23.3,<2
    - scipy >=1.10.1
    - pymatgen >2022.9.21
    - seaborn >=0.13.0
    - matplotlib-base >=3.7.1
    - scikit-learn >=1.3.0
    - umap-learn >=0.5.3
    - adjusttext >=0.8
    - opentsne >=1.0.0
    - typing-extensions

test:
  imports:
    - elementembeddings
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/WMD-group/ElementEmbeddings
  summary: Python package to interact with high-dimensional representations of the chemical elements
  description: |
    The Element Embeddings package provides high-level tools for analysing elemental embeddings data.
    This primarily involves visualising the correlation between embedding schemes using different statistical measures.
  license: MIT
  license_file: LICENSE.md
  doc_url: https://wmd-group.github.io/ElementEmbeddings/stable/
  dev_url: https://github.com/WMD-group/ElementEmbeddings

extra:
  recipe-maintainers:
    - AntObi
